auto: true

markdown: rdiscount
pygments: true
paginate: 5
paginate_path: "page:num"
encoding: UTF-8
permalink: /:title

title: Bruce.com
url: http://luweien.github.io/
feed: /atom.xml
author_info: <a href="http://luweien.github.io/">Bruce</a>
