markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "Bruce's Space"
markdown: rdiscount

author: "luweien"
atom-baseurl: "http://luweien.github.com"
disqus: "luweien"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: 
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

